#!/bin/bash
# Auth: happylife
# Desc: v2ray installation script
# Plat: ubuntu 18.04+
# Eg  : bash v2ray_installation_vmess.sh "你的域名" [vless]

apt update -y 
apt install -y curl 
apt install -y socat
curl https://get.acme.sh | sh
~/.acme.sh/acme.sh --register-account -m example@gmail.com
~/.acme.sh/acme.sh --issue -d 你的域名 --standalone
~/.acme.sh/acme.sh --installcert -d 你的域名 --key-file /root/private.key --fullchain-file /root/cert.crt
